# Generated by Django 4.2 on 2024-05-22 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_rename_phonenumber_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_location', models.CharField(max_length=100)),
                ('dst_location', models.CharField(max_length=100)),
                ('total_fare', models.IntegerField()),
                ('num_passengers', models.IntegerField()),
                ('start_datetime', models.DateTimeField(default=datetime.datetime(2024, 5, 22, 9, 46, 42, 182452))),
                ('user_initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.profile')),
            ],
        ),
    ]
