# Generated by Django 4.2 on 2024-05-22 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='start_datetime',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 22, 9, 46, 51, 237530)),
        ),
    ]
