# Generated by Django 4.2 on 2024-05-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_phonenumber_profile_phone_number'),
        ('ride', '0003_alter_ride_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='user_initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_creator', to='user.profile'),
        ),
    ]
