# Generated by Django 4.2 on 2024-05-12 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(
                    blank=True, max_length=128, region=None, unique=True)),
            ],
        ),
    ]
